name: Collections Suggest Mode
version: 1.0.0
description: Suggest Mode for list of available collections
url: https://github.com/lesaff/statamicv2-suggestmodes
developer: Rudy Affandi
developer_url: https://github.com/lesaff
