name: States and Provinces (Abbreviated)
version: 1.0.0
description: Suggest Mode for US States and Canadian Provinces (Abbreviated)
url: https://github.com/lesaff/statamicv2-states-provinces-abbr
developer: Rudy Affandi
developer_url: https://github.com/lesaff
