name: States and Provinces Suggest Mode
version: 1.0.1
description: Suggest Mode for US States and Canadian Provinces (Full and abbreviated)
url: https://github.com/lesaff/statamicv2-suggestmodes
developer: Rudy Affandi
developer_url: https://github.com/lesaff
