<?php namespace Statamic\Addons\CountriesIso3;

use Statamic\Addons\Suggest\Modes\AbstractMode;

class CountriesIso3SuggestMode extends AbstractMode
{
    public function suggestions()
    {
        
        return [
            ["value" => "ABW", "text" => "ABW - Aruba"],
            ["value" => "AFG", "text" => "AFG - Afghanistan"],
            ["value" => "AGO", "text" => "AGO - Angola"],
            ["value" => "AIA", "text" => "AIA - Anguilla"],
            ["value" => "ALA", "text" => "ALA - Åland Islands"],
            ["value" => "ALB", "text" => "ALB - Albania"],
            ["value" => "AND", "text" => "AND - Andorra"],
            ["value" => "ARE", "text" => "ARE - United Arab Emirates"],
            ["value" => "ARG", "text" => "ARG - Argentina"],
            ["value" => "ARM", "text" => "ARM - Armenia"],
            ["value" => "ASM", "text" => "ASM - American Samoa"],
            ["value" => "ATA", "text" => "ATA - Antarctica"],
            ["value" => "ATF", "text" => "ATF - French Southern Territories"],
            ["value" => "ATG", "text" => "ATG - Antigua and Barbuda"],
            ["value" => "AUS", "text" => "AUS - Australia"],
            ["value" => "AUT", "text" => "AUT - Austria"],
            ["value" => "AZE", "text" => "AZE - Azerbaijan"],
            ["value" => "BDI", "text" => "BDI - Burundi"],
            ["value" => "BEL", "text" => "BEL - Belgium"],
            ["value" => "BEN", "text" => "BEN - Benin"],
            ["value" => "BES", "text" => "BES - Bonaire, Sint Eustatius and Saba"],
            ["value" => "BFA", "text" => "BFA - Burkina Faso"],
            ["value" => "BGD", "text" => "BGD - Bangladesh"],
            ["value" => "BGR", "text" => "BGR - Bulgaria"],
            ["value" => "BHR", "text" => "BHR - Bahrain"],
            ["value" => "BHS", "text" => "BHS - Bahamas"],
            ["value" => "BIH", "text" => "BIH - Bosnia and Herzegovina"],
            ["value" => "BLM", "text" => "BLM - Saint Barthélemy"],
            ["value" => "BLR", "text" => "BLR - Belarus"],
            ["value" => "BLZ", "text" => "BLZ - Belize"],
            ["value" => "BMU", "text" => "BMU - Bermuda"],
            ["value" => "BOL", "text" => "BOL - Bolivia, Plurinational State of"],
            ["value" => "BRA", "text" => "BRA - Brazil"],
            ["value" => "BRB", "text" => "BRB - Barbados"],
            ["value" => "BRN", "text" => "BRN - Brunei Darussalam"],
            ["value" => "BTN", "text" => "BTN - Bhutan"],
            ["value" => "BVT", "text" => "BVT - Bouvet Island"],
            ["value" => "BWA", "text" => "BWA - Botswana"],
            ["value" => "CAF", "text" => "CAF - Central African Republic"],
            ["value" => "CAN", "text" => "CAN - Canada"],
            ["value" => "CCK", "text" => "CCK - Cocos (Keeling) Islands"],
            ["value" => "CHE", "text" => "CHE - Switzerland"],
            ["value" => "CHL", "text" => "CHL - Chile"],
            ["value" => "CHN", "text" => "CHN - China"],
            ["value" => "CIV", "text" => "CIV - Côte d\'Ivoire"],
            ["value" => "CMR", "text" => "CMR - Cameroon"],
            ["value" => "COD", "text" => "COD - Congo, the Democratic Republic of the"],
            ["value" => "COG", "text" => "COG - Congo"],
            ["value" => "COK", "text" => "COK - Cook Islands"],
            ["value" => "COL", "text" => "COL - Colombia"],
            ["value" => "COM", "text" => "COM - Comoros"],
            ["value" => "CPV", "text" => "CPV - Cape Verde"],
            ["value" => "CRI", "text" => "CRI - Costa Rica"],
            ["value" => "CUB", "text" => "CUB - Cuba"],
            ["value" => "CUW", "text" => "CUW - Curaçao"],
            ["value" => "CXR", "text" => "CXR - Christmas Island"],
            ["value" => "CYM", "text" => "CYM - Cayman Islands"],
            ["value" => "CYP", "text" => "CYP - Cyprus"],
            ["value" => "CZE", "text" => "CZE - Czech Republic"],
            ["value" => "DEU", "text" => "DEU - Germany"],
            ["value" => "DJI", "text" => "DJI - Djibouti"],
            ["value" => "DMA", "text" => "DMA - Dominica"],
            ["value" => "DNK", "text" => "DNK - Denmark"],
            ["value" => "DOM", "text" => "DOM - Dominican Republic"],
            ["value" => "DZA", "text" => "DZA - Algeria"],
            ["value" => "ECU", "text" => "ECU - Ecuador"],
            ["value" => "EGY", "text" => "EGY - Egypt"],
            ["value" => "ERI", "text" => "ERI - Eritrea"],
            ["value" => "ESH", "text" => "ESH - Western Sahara"],
            ["value" => "ESP", "text" => "ESP - Spain"],
            ["value" => "EST", "text" => "EST - Estonia"],
            ["value" => "ETH", "text" => "ETH - Ethiopia"],
            ["value" => "FIN", "text" => "FIN - Finland"],
            ["value" => "FJI", "text" => "FJI - Fiji"],
            ["value" => "FLK", "text" => "FLK - Falkland Islands (Malvinas)"],
            ["value" => "FRA", "text" => "FRA - France"],
            ["value" => "FRO", "text" => "FRO - Faroe Islands"],
            ["value" => "FSM", "text" => "FSM - Micronesia, Federated States of"],
            ["value" => "GAB", "text" => "GAB - Gabon"],
            ["value" => "GBR", "text" => "GBR - United Kingdom"],
            ["value" => "GEO", "text" => "GEO - Georgia"],
            ["value" => "GGY", "text" => "GGY - Guernsey"],
            ["value" => "GHA", "text" => "GHA - Ghana"],
            ["value" => "GIB", "text" => "GIB - Gibraltar"],
            ["value" => "GIN", "text" => "GIN - Guinea"],
            ["value" => "GLP", "text" => "GLP - Guadeloupe"],
            ["value" => "GMB", "text" => "GMB - Gambia"],
            ["value" => "GNB", "text" => "GNB - Guinea-Bissau"],
            ["value" => "GNQ", "text" => "GNQ - Equatorial Guinea"],
            ["value" => "GRC", "text" => "GRC - Greece"],
            ["value" => "GRD", "text" => "GRD - Grenada"],
            ["value" => "GRL", "text" => "GRL - Greenland"],
            ["value" => "GTM", "text" => "GTM - Guatemala"],
            ["value" => "GUF", "text" => "GUF - French Guiana"],
            ["value" => "GUM", "text" => "GUM - Guam"],
            ["value" => "GUY", "text" => "GUY - Guyana"],
            ["value" => "HKG", "text" => "HKG - Hong Kong"],
            ["value" => "HMD", "text" => "HMD - Heard Island and McDonald Islands"],
            ["value" => "HND", "text" => "HND - Honduras"],
            ["value" => "HRV", "text" => "HRV - Croatia"],
            ["value" => "HTI", "text" => "HTI - Haiti"],
            ["value" => "HUN", "text" => "HUN - Hungary"],
            ["value" => "IDN", "text" => "IDN - Indonesia"],
            ["value" => "IMN", "text" => "IMN - Isle of Man"],
            ["value" => "IND", "text" => "IND - India"],
            ["value" => "IOT", "text" => "IOT - British Indian Ocean Territory"],
            ["value" => "IRL", "text" => "IRL - Ireland"],
            ["value" => "IRN", "text" => "IRN - Iran, Islamic Republic of"],
            ["value" => "IRQ", "text" => "IRQ - Iraq"],
            ["value" => "ISL", "text" => "ISL - Iceland"],
            ["value" => "ISR", "text" => "ISR - Israel"],
            ["value" => "ITA", "text" => "ITA - Italy"],
            ["value" => "JAM", "text" => "JAM - Jamaica"],
            ["value" => "JEY", "text" => "JEY - Jersey"],
            ["value" => "JOR", "text" => "JOR - Jordan"],
            ["value" => "JPN", "text" => "JPN - Japan"],
            ["value" => "KAZ", "text" => "KAZ - Kazakhstan"],
            ["value" => "KEN", "text" => "KEN - Kenya"],
            ["value" => "KGZ", "text" => "KGZ - Kyrgyzstan"],
            ["value" => "KHM", "text" => "KHM - Cambodia"],
            ["value" => "KIR", "text" => "KIR - Kiribati"],
            ["value" => "KNA", "text" => "KNA - Saint Kitts and Nevis"],
            ["value" => "KOR", "text" => "KOR - Korea, Republic of"],
            ["value" => "KWT", "text" => "KWT - Kuwait"],
            ["value" => "LAO", "text" => "LAO - Lao People\'s Democratic Republic"],
            ["value" => "LBN", "text" => "LBN - Lebanon"],
            ["value" => "LBR", "text" => "LBR - Liberia"],
            ["value" => "LBY", "text" => "LBY - Libya"],
            ["value" => "LCA", "text" => "LCA - Saint Lucia"],
            ["value" => "LIE", "text" => "LIE - Liechtenstein"],
            ["value" => "LKA", "text" => "LKA - Sri Lanka"],
            ["value" => "LSO", "text" => "LSO - Lesotho"],
            ["value" => "LTU", "text" => "LTU - Lithuania"],
            ["value" => "LUX", "text" => "LUX - Luxembourg"],
            ["value" => "LVA", "text" => "LVA - Latvia"],
            ["value" => "MAC", "text" => "MAC - Macao"],
            ["value" => "MAF", "text" => "MAF - Saint Martin (French part)"],
            ["value" => "MAR", "text" => "MAR - Morocco"],
            ["value" => "MCO", "text" => "MCO - Monaco"],
            ["value" => "MDA", "text" => "MDA - Moldova, Republic of"],
            ["value" => "MDG", "text" => "MDG - Madagascar"],
            ["value" => "MDV", "text" => "MDV - Maldives"],
            ["value" => "MEX", "text" => "MEX - Mexico"],
            ["value" => "MHL", "text" => "MHL - Marshall Islands"],
            ["value" => "MKD", "text" => "MKD - Macedonia, the former Yugoslav Republic of"],
            ["value" => "MLI", "text" => "MLI - Mali"],
            ["value" => "MLT", "text" => "MLT - Malta"],
            ["value" => "MMR", "text" => "MMR - Myanmar"],
            ["value" => "MNE", "text" => "MNE - Montenegro"],
            ["value" => "MNG", "text" => "MNG - Mongolia"],
            ["value" => "MNP", "text" => "MNP - Northern Mariana Islands"],
            ["value" => "MOZ", "text" => "MOZ - Mozambique"],
            ["value" => "MRT", "text" => "MRT - Mauritania"],
            ["value" => "MSR", "text" => "MSR - Montserrat"],
            ["value" => "MTQ", "text" => "MTQ - Martinique"],
            ["value" => "MUS", "text" => "MUS - Mauritius"],
            ["value" => "MWI", "text" => "MWI - Malawi"],
            ["value" => "MYS", "text" => "MYS - Malaysia"],
            ["value" => "MYT", "text" => "MYT - Mayotte"],
            ["value" => "NAM", "text" => "NAM - Namibia"],
            ["value" => "NCL", "text" => "NCL - New Caledonia"],
            ["value" => "NER", "text" => "NER - Niger"],
            ["value" => "NFK", "text" => "NFK - Norfolk Island"],
            ["value" => "NGA", "text" => "NGA - Nigeria"],
            ["value" => "NIC", "text" => "NIC - Nicaragua"],
            ["value" => "NIU", "text" => "NIU - Niue"],
            ["value" => "NLD", "text" => "NLD - Netherlands"],
            ["value" => "NOR", "text" => "NOR - Norway"],
            ["value" => "NPL", "text" => "NPL - Nepal"],
            ["value" => "NRU", "text" => "NRU - Nauru"],
            ["value" => "NZL", "text" => "NZL - New Zealand"],
            ["value" => "OMN", "text" => "OMN - Oman"],
            ["value" => "PAK", "text" => "PAK - Pakistan"],
            ["value" => "PAN", "text" => "PAN - Panama"],
            ["value" => "PCN", "text" => "PCN - Pitcairn"],
            ["value" => "PER", "text" => "PER - Peru"],
            ["value" => "PHL", "text" => "PHL - Philippines"],
            ["value" => "PLW", "text" => "PLW - Palau"],
            ["value" => "PNG", "text" => "PNG - Papua New Guinea"],
            ["value" => "POL", "text" => "POL - Poland"],
            ["value" => "PRI", "text" => "PRI - Puerto Rico"],
            ["value" => "PRK", "text" => "PRK - Korea, Democratic People\'s Republic of"],
            ["value" => "PRT", "text" => "PRT - Portugal"],
            ["value" => "PRY", "text" => "PRY - Paraguay"],
            ["value" => "PSE", "text" => "PSE - Palestinian Territory, Occupied"],
            ["value" => "PYF", "text" => "PYF - French Polynesia"],
            ["value" => "QAT", "text" => "QAT - Qatar"],
            ["value" => "REU", "text" => "REU - Réunion"],
            ["value" => "ROU", "text" => "ROU - Romania"],
            ["value" => "RUS", "text" => "RUS - Russian Federation"],
            ["value" => "RWA", "text" => "RWA - Rwanda"],
            ["value" => "SAU", "text" => "SAU - Saudi Arabia"],
            ["value" => "SDN", "text" => "SDN - Sudan"],
            ["value" => "SEN", "text" => "SEN - Senegal"],
            ["value" => "SGP", "text" => "SGP - Singapore"],
            ["value" => "SGS", "text" => "SGS - South Georgia and the South Sandwich Islands"],
            ["value" => "SHN", "text" => "SHN - Saint Helena, Ascension and Tristan da Cunha"],
            ["value" => "SJM", "text" => "SJM - Svalbard and Jan Mayen"],
            ["value" => "SLB", "text" => "SLB - Solomon Islands"],
            ["value" => "SLE", "text" => "SLE - Sierra Leone"],
            ["value" => "SLV", "text" => "SLV - El Salvador"],
            ["value" => "SMR", "text" => "SMR - San Marino"],
            ["value" => "SOM", "text" => "SOM - Somalia"],
            ["value" => "SPM", "text" => "SPM - Saint Pierre and Miquelon"],
            ["value" => "SRB", "text" => "SRB - Serbia"],
            ["value" => "SSD", "text" => "SSD - South Sudan"],
            ["value" => "STP", "text" => "STP - Sao Tome and Principe"],
            ["value" => "SUR", "text" => "SUR - Suriname"],
            ["value" => "SVK", "text" => "SVK - Slovakia"],
            ["value" => "SVN", "text" => "SVN - Slovenia"],
            ["value" => "SWE", "text" => "SWE - Sweden"],
            ["value" => "SWZ", "text" => "SWZ - Swaziland"],
            ["value" => "SXM", "text" => "SXM - Sint Maarten (Dutch part)"],
            ["value" => "SYC", "text" => "SYC - Seychelles"],
            ["value" => "SYR", "text" => "SYR - Syrian Arab Republic"],
            ["value" => "TCA", "text" => "TCA - Turks and Caicos Islands"],
            ["value" => "TCD", "text" => "TCD - Chad"],
            ["value" => "TGO", "text" => "TGO - Togo"],
            ["value" => "THA", "text" => "THA - Thailand"],
            ["value" => "TJK", "text" => "TJK - Tajikistan"],
            ["value" => "TKL", "text" => "TKL - Tokelau"],
            ["value" => "TKM", "text" => "TKM - Turkmenistan"],
            ["value" => "TLS", "text" => "TLS - Timor-Leste"],
            ["value" => "TON", "text" => "TON - Tonga"],
            ["value" => "TTO", "text" => "TTO - Trinidad and Tobago"],
            ["value" => "TUN", "text" => "TUN - Tunisia"],
            ["value" => "TUR", "text" => "TUR - Turkey"],
            ["value" => "TUV", "text" => "TUV - Tuvalu"],
            ["value" => "TWN", "text" => "TWN - Taiwan, Province of China"],
            ["value" => "TZA", "text" => "TZA - Tanzania, United Republic of"],
            ["value" => "UGA", "text" => "UGA - Uganda"],
            ["value" => "UKR", "text" => "UKR - Ukraine"],
            ["value" => "UMI", "text" => "UMI - United States Minor Outlying Islands"],
            ["value" => "URY", "text" => "URY - Uruguay"],
            ["value" => "USA", "text" => "USA - United States"],
            ["value" => "UZB", "text" => "UZB - Uzbekistan"],
            ["value" => "VAT", "text" => "VAT - Holy See (Vatican City State)"],
            ["value" => "VCT", "text" => "VCT - Saint Vincent and the Grenadines"],
            ["value" => "VEN", "text" => "VEN - Venezuela, Bolivarian Republic of"],
            ["value" => "VGB", "text" => "VGB - Virgin Islands, British"],
            ["value" => "VIR", "text" => "VIR - Virgin Islands, U.S."],
            ["value" => "VNM", "text" => "VNM - Viet Nam"],
            ["value" => "VUT", "text" => "VUT - Vanuatu"],
            ["value" => "WLF", "text" => "WLF - Wallis and Futuna"],
            ["value" => "WSM", "text" => "WSM - Samoa"],
            ["value" => "YEM", "text" => "YEM - Yemen"],
            ["value" => "ZAF", "text" => "ZAF - South Africa"],
            ["value" => "ZMB", "text" => "ZMB - Zambia"],
            ["value" => "ZWE", "text" => "ZWE - Zimbabwe"]
        ];
    }
}