name: Countries ISO 3166-1 alpha-2 Code
version: 1.0.0
description: Suggest Mode for list of world countries in ISO 3166-1 alpha-2 Code
url: https://github.com/lesaff/statamicv2-suggestmodes
developer: Rudy Affandi
developer_url: https://github.com/lesaff
