name: Filtered User Suggest Mode
version: 1.0.0
description: Suggest Mode for users with filter capability
url: https://github.com/lesaff/statamicv2-suggestmodes
developer: Rémy Böhler
developer_url: https://subpixel.ch/
