<?php namespace Statamic\Addons\Countries;

use Statamic\Addons\Suggest\Modes\AbstractMode;

class CountriesSuggestMode extends AbstractMode
{
    public function suggestions()
    {
        
        // Full spelling of country names
        $countries = [
            ["value" => "Afghanistan", "text" => "Afghanistan"],
            ["value" => "Aland Islands ", "text" => "Aland Islands "],
            ["value" => "Albania", "text" => "Albania"],
            ["value" => "Algeria", "text" => "Algeria"],
            ["value" => "American Samoa", "text" => "American Samoa"],
            ["value" => "Andorra", "text" => "Andorra"],
            ["value" => "Angola", "text" => "Angola"],
            ["value" => "Anguilla", "text" => "Anguilla"],
            ["value" => "Antarctica", "text" => "Antarctica"],
            ["value" => "Antigua and Barbuda", "text" => "Antigua and Barbuda"],
            ["value" => "Argentina", "text" => "Argentina"],
            ["value" => "Armenia", "text" => "Armenia"],
            ["value" => "Aruba", "text" => "Aruba"],
            ["value" => "Australia", "text" => "Australia"],
            ["value" => "Austria", "text" => "Austria"],
            ["value" => "Azerbaijan", "text" => "Azerbaijan"],
            ["value" => "Bahamas", "text" => "Bahamas"],
            ["value" => "Bahrain", "text" => "Bahrain"],
            ["value" => "Bangladesh", "text" => "Bangladesh"],
            ["value" => "Barbados", "text" => "Barbados"],
            ["value" => "Belarus", "text" => "Belarus"],
            ["value" => "Belgium", "text" => "Belgium"],
            ["value" => "Belize", "text" => "Belize"],
            ["value" => "Benin", "text" => "Benin"],
            ["value" => "Bermuda", "text" => "Bermuda"],
            ["value" => "Bhutan", "text" => "Bhutan"],
            ["value" => "Bolivia, Plurinational State of", "text" => "Bolivia, Plurinational State of"],
            ["value" => "Bonaire, Sint Eustatius and Saba", "text" => "Bonaire, Sint Eustatius and Saba"],
            ["value" => "Bosnia and Herzegovina", "text" => "Bosnia and Herzegovina"],
            ["value" => "Botswana", "text" => "Botswana"],
            ["value" => "Bouvet Island", "text" => "Bouvet Island"],
            ["value" => "Brazil", "text" => "Brazil"],
            ["value" => "British Indian Ocean Territory", "text" => "British Indian Ocean Territory"],
            ["value" => "Brunei Darussalam", "text" => "Brunei Darussalam"],
            ["value" => "Bulgaria", "text" => "Bulgaria"],
            ["value" => "Burkina Faso", "text" => "Burkina Faso"],
            ["value" => "Burundi", "text" => "Burundi"],
            ["value" => "Cambodia", "text" => "Cambodia"],
            ["value" => "Cameroon", "text" => "Cameroon"],
            ["value" => "Canada", "text" => "Canada"],
            ["value" => "Cape Verde", "text" => "Cape Verde"],
            ["value" => "Cayman Islands", "text" => "Cayman Islands"],
            ["value" => "Central African Republic", "text" => "Central African Republic"],
            ["value" => "Chad", "text" => "Chad"],
            ["value" => "Chile", "text" => "Chile"],
            ["value" => "China", "text" => "China"],
            ["value" => "Christmas Island", "text" => "Christmas Island"],
            ["value" => "Cocos (Keeling) Islands", "text" => "Cocos (Keeling) Islands"],
            ["value" => "Colombia", "text" => "Colombia"],
            ["value" => "Comoros", "text" => "Comoros"],
            ["value" => "Congo", "text" => "Congo"],
            ["value" => "Congo, the Democratic Republic of the", "text" => "Congo, the Democratic Republic of the"],
            ["value" => "Cook Islands", "text" => "Cook Islands"],
            ["value" => "Costa Rica", "text" => "Costa Rica"],
            ["value" => "Cote d'Ivoire", "text" => "Cote d'Ivoire"],
            ["value" => "Croatia", "text" => "Croatia"],
            ["value" => "Cuba", "text" => "Cuba"],
            ["value" => "Curaçao", "text" => "Curaçao"],
            ["value" => "Cyprus", "text" => "Cyprus"],
            ["value" => "Czech Republic", "text" => "Czech Republic"],
            ["value" => "Denmark", "text" => "Denmark"],
            ["value" => "Djibouti", "text" => "Djibouti"],
            ["value" => "Dominica", "text" => "Dominica"],
            ["value" => "Dominican Republic", "text" => "Dominican Republic"],
            ["value" => "Ecuador", "text" => "Ecuador"],
            ["value" => "Egypt", "text" => "Egypt"],
            ["value" => "El Salvador", "text" => "El Salvador"],
            ["value" => "Equatorial Guinea", "text" => "Equatorial Guinea"],
            ["value" => "Eritrea", "text" => "Eritrea"],
            ["value" => "Estonia", "text" => "Estonia"],
            ["value" => "Ethiopia", "text" => "Ethiopia"],
            ["value" => "Falkland Islands (Malvinas)", "text" => "Falkland Islands (Malvinas)"],
            ["value" => "Faroe Islands", "text" => "Faroe Islands"],
            ["value" => "Fiji", "text" => "Fiji"],
            ["value" => "Finland", "text" => "Finland"],
            ["value" => "France", "text" => "France"],
            ["value" => "French Guiana", "text" => "French Guiana"],
            ["value" => "French Polynesia", "text" => "French Polynesia"],
            ["value" => "French Southern Territories", "text" => "French Southern Territories"],
            ["value" => "Gabon", "text" => "Gabon"],
            ["value" => "Gambia", "text" => "Gambia"],
            ["value" => "Georgia", "text" => "Georgia"],
            ["value" => "Germany", "text" => "Germany"],
            ["value" => "Ghana", "text" => "Ghana"],
            ["value" => "Gibraltar", "text" => "Gibraltar"],
            ["value" => "Greece", "text" => "Greece"],
            ["value" => "Greenland", "text" => "Greenland"],
            ["value" => "Grenada", "text" => "Grenada"],
            ["value" => "Guadeloupe", "text" => "Guadeloupe"],
            ["value" => "Guam", "text" => "Guam"],
            ["value" => "Guatemala", "text" => "Guatemala"],
            ["value" => "Guernsey", "text" => "Guernsey"],
            ["value" => "Guinea", "text" => "Guinea"],
            ["value" => "Guinea-Bissau", "text" => "Guinea-Bissau"],
            ["value" => "Guyana", "text" => "Guyana"],
            ["value" => "Haiti", "text" => "Haiti"],
            ["value" => "Heard Island and McDonald Islands", "text" => "Heard Island and McDonald Islands"],
            ["value" => "Holy See (Vatican City State)", "text" => "Holy See (Vatican City State)"],
            ["value" => "Honduras", "text" => "Honduras"],
            ["value" => "Hong Kong", "text" => "Hong Kong"],
            ["value" => "Hungary", "text" => "Hungary"],
            ["value" => "Iceland", "text" => "Iceland"],
            ["value" => "India", "text" => "India"],
            ["value" => "Indonesia", "text" => "Indonesia"],
            ["value" => "Iran, Islamic Republic of", "text" => "Iran, Islamic Republic of"],
            ["value" => "Iraq", "text" => "Iraq"],
            ["value" => "Ireland", "text" => "Ireland"],
            ["value" => "Isle of Man", "text" => "Isle of Man"],
            ["value" => "Israel", "text" => "Israel"],
            ["value" => "Italy", "text" => "Italy"],
            ["value" => "Jamaica", "text" => "Jamaica"],
            ["value" => "Japan", "text" => "Japan"],
            ["value" => "Jersey", "text" => "Jersey"],
            ["value" => "Jordan", "text" => "Jordan"],
            ["value" => "Kazakhstan", "text" => "Kazakhstan"],
            ["value" => "Kenya", "text" => "Kenya"],
            ["value" => "Kiribati", "text" => "Kiribati"],
            ["value" => "Korea, Democratic People's Republic of", "text" => "Korea, Democratic People's Republic of"],
            ["value" => "Korea, Republic of", "text" => "Korea, Republic of"],
            ["value" => "Kuwait", "text" => "Kuwait"],
            ["value" => "Kyrgyzstan", "text" => "Kyrgyzstan"],
            ["value" => "Lao People's Democratic Republic", "text" => "Lao People's Democratic Republic"],
            ["value" => "Latvia", "text" => "Latvia"],
            ["value" => "Lebanon", "text" => "Lebanon"],
            ["value" => "Lesotho", "text" => "Lesotho"],
            ["value" => "Liberia", "text" => "Liberia"],
            ["value" => "Libyan Arab Jamahiriya", "text" => "Libyan Arab Jamahiriya"],
            ["value" => "Liechtenstein", "text" => "Liechtenstein"],
            ["value" => "Lithuania", "text" => "Lithuania"],
            ["value" => "Luxembourg", "text" => "Luxembourg"],
            ["value" => "Macao", "text" => "Macao"],
            ["value" => "Macedonia", "text" => "Macedonia"],
            ["value" => "Madagascar", "text" => "Madagascar"],
            ["value" => "Malawi", "text" => "Malawi"],
            ["value" => "Malaysia", "text" => "Malaysia"],
            ["value" => "Maldives", "text" => "Maldives"],
            ["value" => "Mali", "text" => "Mali"],
            ["value" => "Malta", "text" => "Malta"],
            ["value" => "Marshall Islands", "text" => "Marshall Islands"],
            ["value" => "Martinique", "text" => "Martinique"],
            ["value" => "Mauritania", "text" => "Mauritania"],
            ["value" => "Mauritius", "text" => "Mauritius"],
            ["value" => "Mayotte", "text" => "Mayotte"],
            ["value" => "Mexico", "text" => "Mexico"],
            ["value" => "Micronesia, Federated States of", "text" => "Micronesia, Federated States of"],
            ["value" => "Moldova, Republic of", "text" => "Moldova, Republic of"],
            ["value" => "Monaco", "text" => "Monaco"],
            ["value" => "Mongolia", "text" => "Mongolia"],
            ["value" => "Montenegro", "text" => "Montenegro"],
            ["value" => "Montserrat", "text" => "Montserrat"],
            ["value" => "Morocco", "text" => "Morocco"],
            ["value" => "Mozambique", "text" => "Mozambique"],
            ["value" => "Myanmar", "text" => "Myanmar"],
            ["value" => "Namibia", "text" => "Namibia"],
            ["value" => "Nauru", "text" => "Nauru"],
            ["value" => "Nepal", "text" => "Nepal"],
            ["value" => "Netherlands", "text" => "Netherlands"],
            ["value" => "New Caledonia", "text" => "New Caledonia"],
            ["value" => "New Zealand", "text" => "New Zealand"],
            ["value" => "Nicaragua", "text" => "Nicaragua"],
            ["value" => "Niger", "text" => "Niger"],
            ["value" => "Nigeria", "text" => "Nigeria"],
            ["value" => "Niue", "text" => "Niue"],
            ["value" => "Norfolk Island", "text" => "Norfolk Island"],
            ["value" => "Northern Mariana Islands", "text" => "Northern Mariana Islands"],
            ["value" => "Norway", "text" => "Norway"],
            ["value" => "Oman", "text" => "Oman"],
            ["value" => "Pakistan", "text" => "Pakistan"],
            ["value" => "Palau", "text" => "Palau"],
            ["value" => "Palestinian Territory, Occupied", "text" => "Palestinian Territory, Occupied"],
            ["value" => "Panama", "text" => "Panama"],
            ["value" => "Papua New Guinea", "text" => "Papua New Guinea"],
            ["value" => "Paraguay", "text" => "Paraguay"],
            ["value" => "Peru", "text" => "Peru"],
            ["value" => "Philippines", "text" => "Philippines"],
            ["value" => "Pitcairn", "text" => "Pitcairn"],
            ["value" => "Poland", "text" => "Poland"],
            ["value" => "Portugal", "text" => "Portugal"],
            ["value" => "Puerto Rico", "text" => "Puerto Rico"],
            ["value" => "Qatar", "text" => "Qatar"],
            ["value" => "Reunion", "text" => "Reunion"],
            ["value" => "Romania", "text" => "Romania"],
            ["value" => "Russian Federation", "text" => "Russian Federation"],
            ["value" => "Rwanda", "text" => "Rwanda"],
            ["value" => "Saint Barthélemy", "text" => "Saint Barthélemy"],
            ["value" => "Saint Helena", "text" => "Saint Helena"],
            ["value" => "Saint Kitts and Nevis", "text" => "Saint Kitts and Nevis"],
            ["value" => "Saint Lucia", "text" => "Saint Lucia"],
            ["value" => "Saint Martin (French part)", "text" => "Saint Martin (French part)"],
            ["value" => "Saint Pierre and Miquelon", "text" => "Saint Pierre and Miquelon"],
            ["value" => "Saint Vincent and the Grenadines", "text" => "Saint Vincent and the Grenadines"],
            ["value" => "Samoa", "text" => "Samoa"],
            ["value" => "San Marino", "text" => "San Marino"],
            ["value" => "Sao Tome and Principe", "text" => "Sao Tome and Principe"],
            ["value" => "Saudi Arabia", "text" => "Saudi Arabia"],
            ["value" => "Senegal", "text" => "Senegal"],
            ["value" => "Serbia", "text" => "Serbia"],
            ["value" => "Seychelles", "text" => "Seychelles"],
            ["value" => "Sierra Leone", "text" => "Sierra Leone"],
            ["value" => "Singapore", "text" => "Singapore"],
            ["value" => "Sint Maarten (Dutch part)", "text" => "Sint Maarten (Dutch part)"],
            ["value" => "Slovakia", "text" => "Slovakia"],
            ["value" => "Slovenia", "text" => "Slovenia"],
            ["value" => "Solomon Islands", "text" => "Solomon Islands"],
            ["value" => "Somalia", "text" => "Somalia"],
            ["value" => "South Africa", "text" => "South Africa"],
            ["value" => "South Georgia and the South Sandwich Islands", "text" => "South Georgia and the South Sandwich Islands"],
            ["value" => "Spain", "text" => "Spain"],
            ["value" => "Sri Lanka", "text" => "Sri Lanka"],
            ["value" => "Sudan", "text" => "Sudan"],
            ["value" => "Suritext", "text" => "Suritext"],
            ["value" => "Svalbard and Jan Mayen", "text" => "Svalbard and Jan Mayen"],
            ["value" => "Swaziland", "text" => "Swaziland"],
            ["value" => "Sweden", "text" => "Sweden"],
            ["value" => "Switzerland", "text" => "Switzerland"],
            ["value" => "Syrian Arab Republic", "text" => "Syrian Arab Republic"],
            ["value" => "Taiwan, Province of China", "text" => "Taiwan, Province of China"],
            ["value" => "Tajikistan", "text" => "Tajikistan"],
            ["value" => "Tanzania, United Republic of", "text" => "Tanzania, United Republic of"],
            ["value" => "Thailand", "text" => "Thailand"],
            ["value" => "Timor-Leste", "text" => "Timor-Leste"],
            ["value" => "Togo", "text" => "Togo"],
            ["value" => "Tokelau", "text" => "Tokelau"],
            ["value" => "Tonga", "text" => "Tonga"],
            ["value" => "Trinidad and Tobago", "text" => "Trinidad and Tobago"],
            ["value" => "Tunisia", "text" => "Tunisia"],
            ["value" => "Turkey", "text" => "Turkey"],
            ["value" => "Turkmenistan", "text" => "Turkmenistan"],
            ["value" => "Turks and Caicos Islands", "text" => "Turks and Caicos Islands"],
            ["value" => "Tuvalu", "text" => "Tuvalu"],
            ["value" => "Uganda", "text" => "Uganda"],
            ["value" => "Ukraine", "text" => "Ukraine"],
            ["value" => "United Arab Emirates", "text" => "United Arab Emirates"],
            ["value" => "United Kingdom", "text" => "United Kingdom"],
            ["value" => "United States Minor Outlying Islands", "text" => "United States Minor Outlying Islands"],
            ["value" => "United States", "text" => "United States"],
            ["value" => "Uruguay", "text" => "Uruguay"],
            ["value" => "Uzbekistan", "text" => "Uzbekistan"],
            ["value" => "Vanuatu", "text" => "Vanuatu"],
            ["value" => "Venezuela, Bolivarian Republic of", "text" => "Venezuela, Bolivarian Republic of"],
            ["value" => "Viet Nam", "text" => "Viet Nam"],
            ["value" => "Virgin Islands, British", "text" => "Virgin Islands, British"],
            ["value" => "Virgin Islands, U.S.", "text" => "Virgin Islands, U.S."],
            ["value" => "Wallis and Futuna", "text" => "Wallis and Futuna"],
            ["value" => "Western Sahara", "text" => "Western Sahara"],
            ["value" => "Yemen", "text" => "Yemen"],
            ["value" => "Zambia", "text" => "Zambia"],
            ["value" => "Zimbabwe", "text" => "Zimbabwe"]
        ];

        // ISO 3166-1 alpha-2
        $countries_iso2 = [
            ["value" => "AD", "text" => "AD - Andorra"],
            ["value" => "AE", "text" => "AE - United Arab Emirates"],
            ["value" => "AF", "text" => "AF - Afghanistan"],
            ["value" => "AG", "text" => "AG - Antigua and Barbuda"],
            ["value" => "AI", "text" => "AI - Anguilla"],
            ["value" => "AL", "text" => "AL - Albania"],
            ["value" => "AM", "text" => "AM - Armenia"],
            ["value" => "AO", "text" => "AO - Angola"],
            ["value" => "AQ", "text" => "AQ - Antarctica"],
            ["value" => "AR", "text" => "AR - Argentina"],
            ["value" => "AS", "text" => "AS - American Samoa"],
            ["value" => "AT", "text" => "AT - Austria"],
            ["value" => "AU", "text" => "AU - Australia"],
            ["value" => "AW", "text" => "AW - Aruba"],
            ["value" => "AX", "text" => "AX - Aland Islands "],
            ["value" => "AZ", "text" => "AZ - Azerbaijan"],
            ["value" => "BA", "text" => "BA - Bosnia and Herzegovina"],
            ["value" => "BB", "text" => "BB - Barbados"],
            ["value" => "BD", "text" => "BD - Bangladesh"],
            ["value" => "BE", "text" => "BE - Belgium"],
            ["value" => "BF", "text" => "BF - Burkina Faso"],
            ["value" => "BG", "text" => "BG - Bulgaria"],
            ["value" => "BH", "text" => "BH - Bahrain"],
            ["value" => "BI", "text" => "BI - Burundi"],
            ["value" => "BJ", "text" => "BJ - Benin"],
            ["value" => "BL", "text" => "BL - Saint Barthélemy"],
            ["value" => "BM", "text" => "BM - Bermuda"],
            ["value" => "BN", "text" => "BN - Brunei Darussalam"],
            ["value" => "BO", "text" => "BO - Bolivia, Plurinational State of"],
            ["value" => "BQ", "text" => "BQ - Bonaire, Sint Eustatius and Saba"],
            ["value" => "BR", "text" => "BR - Brazil"],
            ["value" => "BS", "text" => "BS - Bahamas"],
            ["value" => "BT", "text" => "BT - Bhutan"],
            ["value" => "BV", "text" => "BV - Bouvet Island"],
            ["value" => "BW", "text" => "BW - Botswana"],
            ["value" => "BY", "text" => "BY - Belarus"],
            ["value" => "BZ", "text" => "BZ - Belize"],
            ["value" => "CA", "text" => "CA - Canada"],
            ["value" => "CC", "text" => "CC - Cocos (Keeling) Islands"],
            ["value" => "CD", "text" => "CD - Congo, the Democratic Republic of the"],
            ["value" => "CF", "text" => "CF - Central African Republic"],
            ["value" => "CG", "text" => "CG - Congo"],
            ["value" => "CH", "text" => "CH - Switzerland"],
            ["value" => "CI", "text" => "CI - Cote d'Ivoire"],
            ["value" => "CK", "text" => "CK - Cook Islands"],
            ["value" => "CL", "text" => "CL - Chile"],
            ["value" => "CM", "text" => "CM - Cameroon"],
            ["value" => "CN", "text" => "CN - China"],
            ["value" => "CO", "text" => "CO - Colombia"],
            ["value" => "CR", "text" => "CR - Costa Rica"],
            ["value" => "CU", "text" => "CU - Cuba"],
            ["value" => "CV", "text" => "CV - Cape Verde"],
            ["value" => "CW", "text" => "CW - Curaçao"],
            ["value" => "CX", "text" => "CX - Christmas Island"],
            ["value" => "CY", "text" => "CY - Cyprus"],
            ["value" => "CZ", "text" => "CZ - Czech Republic"],
            ["value" => "DE", "text" => "DE - Germany"],
            ["value" => "DJ", "text" => "DJ - Djibouti"],
            ["value" => "DK", "text" => "DK - Denmark"],
            ["value" => "DM", "text" => "DM - Dominica"],
            ["value" => "DO", "text" => "DO - Dominican Republic"],
            ["value" => "DZ", "text" => "DZ - Algeria"],
            ["value" => "EC", "text" => "EC - Ecuador"],
            ["value" => "EE", "text" => "EE - Estonia"],
            ["value" => "EG", "text" => "EG - Egypt"],
            ["value" => "EH", "text" => "EH - Western Sahara"],
            ["value" => "ER", "text" => "ER - Eritrea"],
            ["value" => "ES", "text" => "ES - Spain"],
            ["value" => "ET", "text" => "ET - Ethiopia"],
            ["value" => "FI", "text" => "FI - Finland"],
            ["value" => "FJ", "text" => "FJ - Fiji"],
            ["value" => "FK", "text" => "FK - Falkland Islands (Malvinas)"],
            ["value" => "FM", "text" => "FM - Micronesia, Federated States of"],
            ["value" => "FO", "text" => "FO - Faroe Islands"],
            ["value" => "FR", "text" => "FR - France"],
            ["value" => "GA", "text" => "GA - Gabon"],
            ["value" => "GB", "text" => "GB - United Kingdom"],
            ["value" => "GD", "text" => "GD - Grenada"],
            ["value" => "GE", "text" => "GE - Georgia"],
            ["value" => "GF", "text" => "GF - French Guiana"],
            ["value" => "GG", "text" => "GG - Guernsey"],
            ["value" => "GH", "text" => "GH - Ghana"],
            ["value" => "GI", "text" => "GI - Gibraltar"],
            ["value" => "GL", "text" => "GL - Greenland"],
            ["value" => "GM", "text" => "GM - Gambia"],
            ["value" => "GN", "text" => "GN - Guinea"],
            ["value" => "GP", "text" => "GP - Guadeloupe"],
            ["value" => "GQ", "text" => "GQ - Equatorial Guinea"],
            ["value" => "GR", "text" => "GR - Greece"],
            ["value" => "GS", "text" => "GS - South Georgia and the South Sandwich Islands"],
            ["value" => "GT", "text" => "GT - Guatemala"],
            ["value" => "GU", "text" => "GU - Guam"],
            ["value" => "GW", "text" => "GW - Guinea-Bissau"],
            ["value" => "GY", "text" => "GY - Guyana"],
            ["value" => "HK", "text" => "HK - Hong Kong"],
            ["value" => "HM", "text" => "HM - Heard Island and McDonald Islands"],
            ["value" => "HN", "text" => "HN - Honduras"],
            ["value" => "HR", "text" => "HR - Croatia"],
            ["value" => "HT", "text" => "HT - Haiti"],
            ["value" => "HU", "text" => "HU - Hungary"],
            ["value" => "ID", "text" => "ID - Indonesia"],
            ["value" => "IE", "text" => "IE - Ireland"],
            ["value" => "IL", "text" => "IL - Israel"],
            ["value" => "IM", "text" => "IM - Isle of Man"],
            ["value" => "IN", "text" => "IN - India"],
            ["value" => "IO", "text" => "IO - British Indian Ocean Territory"],
            ["value" => "IQ", "text" => "IQ - Iraq"],
            ["value" => "IR", "text" => "IR - Iran, Islamic Republic of"],
            ["value" => "IS", "text" => "IS - Iceland"],
            ["value" => "IT", "text" => "IT - Italy"],
            ["value" => "JE", "text" => "JE - Jersey"],
            ["value" => "JM", "text" => "JM - Jamaica"],
            ["value" => "JO", "text" => "JO - Jordan"],
            ["value" => "JP", "text" => "JP - Japan"],
            ["value" => "KE", "text" => "KE - Kenya"],
            ["value" => "KG", "text" => "KG - Kyrgyzstan"],
            ["value" => "KH", "text" => "KH - Cambodia"],
            ["value" => "KI", "text" => "KI - Kiribati"],
            ["value" => "KM", "text" => "KM - Comoros"],
            ["value" => "KN", "text" => "KN - Saint Kitts and Nevis"],
            ["value" => "KP", "text" => "KP - Korea, Democratic People's Republic of"],
            ["value" => "KR", "text" => "KR - Korea, Republic of"],
            ["value" => "KW", "text" => "KW - Kuwait"],
            ["value" => "KY", "text" => "KY - Cayman Islands"],
            ["value" => "KZ", "text" => "KZ - Kazakhstan"],
            ["value" => "LA", "text" => "LA - Lao People's Democratic Republic"],
            ["value" => "LB", "text" => "LB - Lebanon"],
            ["value" => "LC", "text" => "LC - Saint Lucia"],
            ["value" => "LI", "text" => "LI - Liechtenstein"],
            ["value" => "LK", "text" => "LK - Sri Lanka"],
            ["value" => "LR", "text" => "LR - Liberia"],
            ["value" => "LS", "text" => "LS - Lesotho"],
            ["value" => "LT", "text" => "LT - Lithuania"],
            ["value" => "LU", "text" => "LU - Luxembourg"],
            ["value" => "LV", "text" => "LV - Latvia"],
            ["value" => "LY", "text" => "LY - Libyan Arab Jamahiriya"],
            ["value" => "MA", "text" => "MA - Morocco"],
            ["value" => "MC", "text" => "MC - Monaco"],
            ["value" => "MD", "text" => "MD - Moldova, Republic of"],
            ["value" => "ME", "text" => "ME - Montenegro"],
            ["value" => "MF", "text" => "MF - Saint Martin (French part)"],
            ["value" => "MG", "text" => "MG - Madagascar"],
            ["value" => "MH", "text" => "MH - Marshall Islands"],
            ["value" => "MK", "text" => "MK - Macedonia"],
            ["value" => "ML", "text" => "ML - Mali"],
            ["value" => "MM", "text" => "MM - Myanmar"],
            ["value" => "MN", "text" => "MN - Mongolia"],
            ["value" => "MO", "text" => "MO - Macao"],
            ["value" => "MP", "text" => "MP - Northern Mariana Islands"],
            ["value" => "MQ", "text" => "MQ - Martinique"],
            ["value" => "MR", "text" => "MR - Mauritania"],
            ["value" => "MS", "text" => "MS - Montserrat"],
            ["value" => "MT", "text" => "MT - Malta"],
            ["value" => "MU", "text" => "MU - Mauritius"],
            ["value" => "MV", "text" => "MV - Maldives"],
            ["value" => "MW", "text" => "MW - Malawi"],
            ["value" => "MX", "text" => "MX - Mexico"],
            ["value" => "MY", "text" => "MY - Malaysia"],
            ["value" => "MZ", "text" => "MZ - Mozambique"],
            ["value" => "NA", "text" => "NA - Namibia"],
            ["value" => "NC", "text" => "NC - New Caledonia"],
            ["value" => "NE", "text" => "NE - Niger"],
            ["value" => "NF", "text" => "NF - Norfolk Island"],
            ["value" => "NG", "text" => "NG - Nigeria"],
            ["value" => "NI", "text" => "NI - Nicaragua"],
            ["value" => "NL", "text" => "NL - Netherlands"],
            ["value" => "NO", "text" => "NO - Norway"],
            ["value" => "NP", "text" => "NP - Nepal"],
            ["value" => "NR", "text" => "NR - Nauru"],
            ["value" => "NU", "text" => "NU - Niue"],
            ["value" => "NZ", "text" => "NZ - New Zealand"],
            ["value" => "OM", "text" => "OM - Oman"],
            ["value" => "PA", "text" => "PA - Panama"],
            ["value" => "PE", "text" => "PE - Peru"],
            ["value" => "PF", "text" => "PF - French Polynesia"],
            ["value" => "PG", "text" => "PG - Papua New Guinea"],
            ["value" => "PH", "text" => "PH - Philippines"],
            ["value" => "PK", "text" => "PK - Pakistan"],
            ["value" => "PL", "text" => "PL - Poland"],
            ["value" => "PM", "text" => "PM - Saint Pierre and Miquelon"],
            ["value" => "PN", "text" => "PN - Pitcairn"],
            ["value" => "PR", "text" => "PR - Puerto Rico"],
            ["value" => "PS", "text" => "PS - Palestinian Territory, Occupied"],
            ["value" => "PT", "text" => "PT - Portugal"],
            ["value" => "PW", "text" => "PW - Palau"],
            ["value" => "PY", "text" => "PY - Paraguay"],
            ["value" => "QA", "text" => "QA - Qatar"],
            ["value" => "RE", "text" => "RE - Reunion"],
            ["value" => "RO", "text" => "RO - Romania"],
            ["value" => "RS", "text" => "RS - Serbia"],
            ["value" => "RU", "text" => "RU - Russian Federation"],
            ["value" => "RW", "text" => "RW - Rwanda"],
            ["value" => "SA", "text" => "SA - Saudi Arabia"],
            ["value" => "SB", "text" => "SB - Solomon Islands"],
            ["value" => "SC", "text" => "SC - Seychelles"],
            ["value" => "SD", "text" => "SD - Sudan"],
            ["value" => "SE", "text" => "SE - Sweden"],
            ["value" => "SG", "text" => "SG - Singapore"],
            ["value" => "SH", "text" => "SH - Saint Helena"],
            ["value" => "SI", "text" => "SI - Slovenia"],
            ["value" => "SJ", "text" => "SJ - Svalbard and Jan Mayen"],
            ["value" => "SK", "text" => "SK - Slovakia"],
            ["value" => "SL", "text" => "SL - Sierra Leone"],
            ["value" => "SM", "text" => "SM - San Marino"],
            ["value" => "SN", "text" => "SN - Senegal"],
            ["value" => "SO", "text" => "SO - Somalia"],
            ["value" => "SR", "text" => "SR - Suritext"],
            ["value" => "ST", "text" => "ST - Sao Tome and Principe"],
            ["value" => "SV", "text" => "SV - El Salvador"],
            ["value" => "SX", "text" => "SX - Sint Maarten (Dutch part)"],
            ["value" => "SY", "text" => "SY - Syrian Arab Republic"],
            ["value" => "SZ", "text" => "SZ - Swaziland"],
            ["value" => "TC", "text" => "TC - Turks and Caicos Islands"],
            ["value" => "TD", "text" => "TD - Chad"],
            ["value" => "TF", "text" => "TF - French Southern Territories"],
            ["value" => "TG", "text" => "TG - Togo"],
            ["value" => "TH", "text" => "TH - Thailand"],
            ["value" => "TJ", "text" => "TJ - Tajikistan"],
            ["value" => "TK", "text" => "TK - Tokelau"],
            ["value" => "TL", "text" => "TL - Timor-Leste"],
            ["value" => "TM", "text" => "TM - Turkmenistan"],
            ["value" => "TN", "text" => "TN - Tunisia"],
            ["value" => "TO", "text" => "TO - Tonga"],
            ["value" => "TR", "text" => "TR - Turkey"],
            ["value" => "TT", "text" => "TT - Trinidad and Tobago"],
            ["value" => "TV", "text" => "TV - Tuvalu"],
            ["value" => "TW", "text" => "TW - Taiwan, Province of China"],
            ["value" => "TZ", "text" => "TZ - Tanzania, United Republic of"],
            ["value" => "UA", "text" => "UA - Ukraine"],
            ["value" => "UG", "text" => "UG - Uganda"],
            ["value" => "UM", "text" => "UM - United States Minor Outlying Islands"],
            ["value" => "US", "text" => "US - United States"],
            ["value" => "UY", "text" => "UY - Uruguay"],
            ["value" => "UZ", "text" => "UZ - Uzbekistan"],
            ["value" => "VA", "text" => "VA - Holy See (Vatican City State)"],
            ["value" => "VC", "text" => "VC - Saint Vincent and the Grenadines"],
            ["value" => "VE", "text" => "VE - Venezuela, Bolivarian Republic of"],
            ["value" => "VG", "text" => "VG - Virgin Islands, British"],
            ["value" => "VI", "text" => "VI - Virgin Islands, U.S."],
            ["value" => "VN", "text" => "VN - Viet Nam"],
            ["value" => "VU", "text" => "VU - Vanuatu"],
            ["value" => "WF", "text" => "WF - Wallis and Futuna"],
            ["value" => "WS", "text" => "WS - Samoa"],
            ["value" => "YE", "text" => "YE - Yemen"],
            ["value" => "YT", "text" => "YT - Mayotte"],
            ["value" => "ZA", "text" => "ZA - South Africa"],
            ["value" => "ZM", "text" => "ZM - Zambia"],
            ["value" => "ZW", "text" => "ZW - Zimbabwe"]
        ];

        // ISO 3166-1 alpha 3
        $countries_iso3 = [
            ["value" => "ABW", "text" => "ABW - Aruba"],
            ["value" => "AFG", "text" => "AFG - Afghanistan"],
            ["value" => "AGO", "text" => "AGO - Angola"],
            ["value" => "AIA", "text" => "AIA - Anguilla"],
            ["value" => "ALA", "text" => "ALA - Åland Islands"],
            ["value" => "ALB", "text" => "ALB - Albania"],
            ["value" => "AND", "text" => "AND - Andorra"],
            ["value" => "ARE", "text" => "ARE - United Arab Emirates"],
            ["value" => "ARG", "text" => "ARG - Argentina"],
            ["value" => "ARM", "text" => "ARM - Armenia"],
            ["value" => "ASM", "text" => "ASM - American Samoa"],
            ["value" => "ATA", "text" => "ATA - Antarctica"],
            ["value" => "ATF", "text" => "ATF - French Southern Territories"],
            ["value" => "ATG", "text" => "ATG - Antigua and Barbuda"],
            ["value" => "AUS", "text" => "AUS - Australia"],
            ["value" => "AUT", "text" => "AUT - Austria"],
            ["value" => "AZE", "text" => "AZE - Azerbaijan"],
            ["value" => "BDI", "text" => "BDI - Burundi"],
            ["value" => "BEL", "text" => "BEL - Belgium"],
            ["value" => "BEN", "text" => "BEN - Benin"],
            ["value" => "BES", "text" => "BES - Bonaire, Sint Eustatius and Saba"],
            ["value" => "BFA", "text" => "BFA - Burkina Faso"],
            ["value" => "BGD", "text" => "BGD - Bangladesh"],
            ["value" => "BGR", "text" => "BGR - Bulgaria"],
            ["value" => "BHR", "text" => "BHR - Bahrain"],
            ["value" => "BHS", "text" => "BHS - Bahamas"],
            ["value" => "BIH", "text" => "BIH - Bosnia and Herzegovina"],
            ["value" => "BLM", "text" => "BLM - Saint Barthélemy"],
            ["value" => "BLR", "text" => "BLR - Belarus"],
            ["value" => "BLZ", "text" => "BLZ - Belize"],
            ["value" => "BMU", "text" => "BMU - Bermuda"],
            ["value" => "BOL", "text" => "BOL - Bolivia, Plurinational State of"],
            ["value" => "BRA", "text" => "BRA - Brazil"],
            ["value" => "BRB", "text" => "BRB - Barbados"],
            ["value" => "BRN", "text" => "BRN - Brunei Darussalam"],
            ["value" => "BTN", "text" => "BTN - Bhutan"],
            ["value" => "BVT", "text" => "BVT - Bouvet Island"],
            ["value" => "BWA", "text" => "BWA - Botswana"],
            ["value" => "CAF", "text" => "CAF - Central African Republic"],
            ["value" => "CAN", "text" => "CAN - Canada"],
            ["value" => "CCK", "text" => "CCK - Cocos (Keeling) Islands"],
            ["value" => "CHE", "text" => "CHE - Switzerland"],
            ["value" => "CHL", "text" => "CHL - Chile"],
            ["value" => "CHN", "text" => "CHN - China"],
            ["value" => "CIV", "text" => "CIV - Côte d'Ivoire"],
            ["value" => "CMR", "text" => "CMR - Cameroon"],
            ["value" => "COD", "text" => "COD - Congo, the Democratic Republic of the"],
            ["value" => "COG", "text" => "COG - Congo"],
            ["value" => "COK", "text" => "COK - Cook Islands"],
            ["value" => "COL", "text" => "COL - Colombia"],
            ["value" => "COM", "text" => "COM - Comoros"],
            ["value" => "CPV", "text" => "CPV - Cape Verde"],
            ["value" => "CRI", "text" => "CRI - Costa Rica"],
            ["value" => "CUB", "text" => "CUB - Cuba"],
            ["value" => "CUW", "text" => "CUW - Curaçao"],
            ["value" => "CXR", "text" => "CXR - Christmas Island"],
            ["value" => "CYM", "text" => "CYM - Cayman Islands"],
            ["value" => "CYP", "text" => "CYP - Cyprus"],
            ["value" => "CZE", "text" => "CZE - Czech Republic"],
            ["value" => "DEU", "text" => "DEU - Germany"],
            ["value" => "DJI", "text" => "DJI - Djibouti"],
            ["value" => "DMA", "text" => "DMA - Dominica"],
            ["value" => "DNK", "text" => "DNK - Denmark"],
            ["value" => "DOM", "text" => "DOM - Dominican Republic"],
            ["value" => "DZA", "text" => "DZA - Algeria"],
            ["value" => "ECU", "text" => "ECU - Ecuador"],
            ["value" => "EGY", "text" => "EGY - Egypt"],
            ["value" => "ERI", "text" => "ERI - Eritrea"],
            ["value" => "ESH", "text" => "ESH - Western Sahara"],
            ["value" => "ESP", "text" => "ESP - Spain"],
            ["value" => "EST", "text" => "EST - Estonia"],
            ["value" => "ETH", "text" => "ETH - Ethiopia"],
            ["value" => "FIN", "text" => "FIN - Finland"],
            ["value" => "FJI", "text" => "FJI - Fiji"],
            ["value" => "FLK", "text" => "FLK - Falkland Islands (Malvinas)"],
            ["value" => "FRA", "text" => "FRA - France"],
            ["value" => "FRO", "text" => "FRO - Faroe Islands"],
            ["value" => "FSM", "text" => "FSM - Micronesia, Federated States of"],
            ["value" => "GAB", "text" => "GAB - Gabon"],
            ["value" => "GBR", "text" => "GBR - United Kingdom"],
            ["value" => "GEO", "text" => "GEO - Georgia"],
            ["value" => "GGY", "text" => "GGY - Guernsey"],
            ["value" => "GHA", "text" => "GHA - Ghana"],
            ["value" => "GIB", "text" => "GIB - Gibraltar"],
            ["value" => "GIN", "text" => "GIN - Guinea"],
            ["value" => "GLP", "text" => "GLP - Guadeloupe"],
            ["value" => "GMB", "text" => "GMB - Gambia"],
            ["value" => "GNB", "text" => "GNB - Guinea-Bissau"],
            ["value" => "GNQ", "text" => "GNQ - Equatorial Guinea"],
            ["value" => "GRC", "text" => "GRC - Greece"],
            ["value" => "GRD", "text" => "GRD - Grenada"],
            ["value" => "GRL", "text" => "GRL - Greenland"],
            ["value" => "GTM", "text" => "GTM - Guatemala"],
            ["value" => "GUF", "text" => "GUF - French Guiana"],
            ["value" => "GUM", "text" => "GUM - Guam"],
            ["value" => "GUY", "text" => "GUY - Guyana"],
            ["value" => "HKG", "text" => "HKG - Hong Kong"],
            ["value" => "HMD", "text" => "HMD - Heard Island and McDonald Islands"],
            ["value" => "HND", "text" => "HND - Honduras"],
            ["value" => "HRV", "text" => "HRV - Croatia"],
            ["value" => "HTI", "text" => "HTI - Haiti"],
            ["value" => "HUN", "text" => "HUN - Hungary"],
            ["value" => "IDN", "text" => "IDN - Indonesia"],
            ["value" => "IMN", "text" => "IMN - Isle of Man"],
            ["value" => "IND", "text" => "IND - India"],
            ["value" => "IOT", "text" => "IOT - British Indian Ocean Territory"],
            ["value" => "IRL", "text" => "IRL - Ireland"],
            ["value" => "IRN", "text" => "IRN - Iran, Islamic Republic of"],
            ["value" => "IRQ", "text" => "IRQ - Iraq"],
            ["value" => "ISL", "text" => "ISL - Iceland"],
            ["value" => "ISR", "text" => "ISR - Israel"],
            ["value" => "ITA", "text" => "ITA - Italy"],
            ["value" => "JAM", "text" => "JAM - Jamaica"],
            ["value" => "JEY", "text" => "JEY - Jersey"],
            ["value" => "JOR", "text" => "JOR - Jordan"],
            ["value" => "JPN", "text" => "JPN - Japan"],
            ["value" => "KAZ", "text" => "KAZ - Kazakhstan"],
            ["value" => "KEN", "text" => "KEN - Kenya"],
            ["value" => "KGZ", "text" => "KGZ - Kyrgyzstan"],
            ["value" => "KHM", "text" => "KHM - Cambodia"],
            ["value" => "KIR", "text" => "KIR - Kiribati"],
            ["value" => "KNA", "text" => "KNA - Saint Kitts and Nevis"],
            ["value" => "KOR", "text" => "KOR - Korea, Republic of"],
            ["value" => "KWT", "text" => "KWT - Kuwait"],
            ["value" => "LAO", "text" => "LAO - Lao People's Democratic Republic"],
            ["value" => "LBN", "text" => "LBN - Lebanon"],
            ["value" => "LBR", "text" => "LBR - Liberia"],
            ["value" => "LBY", "text" => "LBY - Libya"],
            ["value" => "LCA", "text" => "LCA - Saint Lucia"],
            ["value" => "LIE", "text" => "LIE - Liechtenstein"],
            ["value" => "LKA", "text" => "LKA - Sri Lanka"],
            ["value" => "LSO", "text" => "LSO - Lesotho"],
            ["value" => "LTU", "text" => "LTU - Lithuania"],
            ["value" => "LUX", "text" => "LUX - Luxembourg"],
            ["value" => "LVA", "text" => "LVA - Latvia"],
            ["value" => "MAC", "text" => "MAC - Macao"],
            ["value" => "MAF", "text" => "MAF - Saint Martin (French part)"],
            ["value" => "MAR", "text" => "MAR - Morocco"],
            ["value" => "MCO", "text" => "MCO - Monaco"],
            ["value" => "MDA", "text" => "MDA - Moldova, Republic of"],
            ["value" => "MDG", "text" => "MDG - Madagascar"],
            ["value" => "MDV", "text" => "MDV - Maldives"],
            ["value" => "MEX", "text" => "MEX - Mexico"],
            ["value" => "MHL", "text" => "MHL - Marshall Islands"],
            ["value" => "MKD", "text" => "MKD - Macedonia, the former Yugoslav Republic of"],
            ["value" => "MLI", "text" => "MLI - Mali"],
            ["value" => "MLT", "text" => "MLT - Malta"],
            ["value" => "MMR", "text" => "MMR - Myanmar"],
            ["value" => "MNE", "text" => "MNE - Montenegro"],
            ["value" => "MNG", "text" => "MNG - Mongolia"],
            ["value" => "MNP", "text" => "MNP - Northern Mariana Islands"],
            ["value" => "MOZ", "text" => "MOZ - Mozambique"],
            ["value" => "MRT", "text" => "MRT - Mauritania"],
            ["value" => "MSR", "text" => "MSR - Montserrat"],
            ["value" => "MTQ", "text" => "MTQ - Martinique"],
            ["value" => "MUS", "text" => "MUS - Mauritius"],
            ["value" => "MWI", "text" => "MWI - Malawi"],
            ["value" => "MYS", "text" => "MYS - Malaysia"],
            ["value" => "MYT", "text" => "MYT - Mayotte"],
            ["value" => "NAM", "text" => "NAM - Namibia"],
            ["value" => "NCL", "text" => "NCL - New Caledonia"],
            ["value" => "NER", "text" => "NER - Niger"],
            ["value" => "NFK", "text" => "NFK - Norfolk Island"],
            ["value" => "NGA", "text" => "NGA - Nigeria"],
            ["value" => "NIC", "text" => "NIC - Nicaragua"],
            ["value" => "NIU", "text" => "NIU - Niue"],
            ["value" => "NLD", "text" => "NLD - Netherlands"],
            ["value" => "NOR", "text" => "NOR - Norway"],
            ["value" => "NPL", "text" => "NPL - Nepal"],
            ["value" => "NRU", "text" => "NRU - Nauru"],
            ["value" => "NZL", "text" => "NZL - New Zealand"],
            ["value" => "OMN", "text" => "OMN - Oman"],
            ["value" => "PAK", "text" => "PAK - Pakistan"],
            ["value" => "PAN", "text" => "PAN - Panama"],
            ["value" => "PCN", "text" => "PCN - Pitcairn"],
            ["value" => "PER", "text" => "PER - Peru"],
            ["value" => "PHL", "text" => "PHL - Philippines"],
            ["value" => "PLW", "text" => "PLW - Palau"],
            ["value" => "PNG", "text" => "PNG - Papua New Guinea"],
            ["value" => "POL", "text" => "POL - Poland"],
            ["value" => "PRI", "text" => "PRI - Puerto Rico"],
            ["value" => "PRK", "text" => "PRK - Korea, Democratic People's Republic of"],
            ["value" => "PRT", "text" => "PRT - Portugal"],
            ["value" => "PRY", "text" => "PRY - Paraguay"],
            ["value" => "PSE", "text" => "PSE - Palestinian Territory, Occupied"],
            ["value" => "PYF", "text" => "PYF - French Polynesia"],
            ["value" => "QAT", "text" => "QAT - Qatar"],
            ["value" => "REU", "text" => "REU - Réunion"],
            ["value" => "ROU", "text" => "ROU - Romania"],
            ["value" => "RUS", "text" => "RUS - Russian Federation"],
            ["value" => "RWA", "text" => "RWA - Rwanda"],
            ["value" => "SAU", "text" => "SAU - Saudi Arabia"],
            ["value" => "SDN", "text" => "SDN - Sudan"],
            ["value" => "SEN", "text" => "SEN - Senegal"],
            ["value" => "SGP", "text" => "SGP - Singapore"],
            ["value" => "SGS", "text" => "SGS - South Georgia and the South Sandwich Islands"],
            ["value" => "SHN", "text" => "SHN - Saint Helena, Ascension and Tristan da Cunha"],
            ["value" => "SJM", "text" => "SJM - Svalbard and Jan Mayen"],
            ["value" => "SLB", "text" => "SLB - Solomon Islands"],
            ["value" => "SLE", "text" => "SLE - Sierra Leone"],
            ["value" => "SLV", "text" => "SLV - El Salvador"],
            ["value" => "SMR", "text" => "SMR - San Marino"],
            ["value" => "SOM", "text" => "SOM - Somalia"],
            ["value" => "SPM", "text" => "SPM - Saint Pierre and Miquelon"],
            ["value" => "SRB", "text" => "SRB - Serbia"],
            ["value" => "SSD", "text" => "SSD - South Sudan"],
            ["value" => "STP", "text" => "STP - Sao Tome and Principe"],
            ["value" => "SUR", "text" => "SUR - Suriname"],
            ["value" => "SVK", "text" => "SVK - Slovakia"],
            ["value" => "SVN", "text" => "SVN - Slovenia"],
            ["value" => "SWE", "text" => "SWE - Sweden"],
            ["value" => "SWZ", "text" => "SWZ - Swaziland"],
            ["value" => "SXM", "text" => "SXM - Sint Maarten (Dutch part)"],
            ["value" => "SYC", "text" => "SYC - Seychelles"],
            ["value" => "SYR", "text" => "SYR - Syrian Arab Republic"],
            ["value" => "TCA", "text" => "TCA - Turks and Caicos Islands"],
            ["value" => "TCD", "text" => "TCD - Chad"],
            ["value" => "TGO", "text" => "TGO - Togo"],
            ["value" => "THA", "text" => "THA - Thailand"],
            ["value" => "TJK", "text" => "TJK - Tajikistan"],
            ["value" => "TKL", "text" => "TKL - Tokelau"],
            ["value" => "TKM", "text" => "TKM - Turkmenistan"],
            ["value" => "TLS", "text" => "TLS - Timor-Leste"],
            ["value" => "TON", "text" => "TON - Tonga"],
            ["value" => "TTO", "text" => "TTO - Trinidad and Tobago"],
            ["value" => "TUN", "text" => "TUN - Tunisia"],
            ["value" => "TUR", "text" => "TUR - Turkey"],
            ["value" => "TUV", "text" => "TUV - Tuvalu"],
            ["value" => "TWN", "text" => "TWN - Taiwan, Province of China"],
            ["value" => "TZA", "text" => "TZA - Tanzania, United Republic of"],
            ["value" => "UGA", "text" => "UGA - Uganda"],
            ["value" => "UKR", "text" => "UKR - Ukraine"],
            ["value" => "UMI", "text" => "UMI - United States Minor Outlying Islands"],
            ["value" => "URY", "text" => "URY - Uruguay"],
            ["value" => "USA", "text" => "USA - United States"],
            ["value" => "UZB", "text" => "UZB - Uzbekistan"],
            ["value" => "VAT", "text" => "VAT - Holy See (Vatican City State)"],
            ["value" => "VCT", "text" => "VCT - Saint Vincent and the Grenadines"],
            ["value" => "VEN", "text" => "VEN - Venezuela, Bolivarian Republic of"],
            ["value" => "VGB", "text" => "VGB - Virgin Islands, British"],
            ["value" => "VIR", "text" => "VIR - Virgin Islands, U.S."],
            ["value" => "VNM", "text" => "VNM - Viet Nam"],
            ["value" => "VUT", "text" => "VUT - Vanuatu"],
            ["value" => "WLF", "text" => "WLF - Wallis and Futuna"],
            ["value" => "WSM", "text" => "WSM - Samoa"],
            ["value" => "YEM", "text" => "YEM - Yemen"],
            ["value" => "ZAF", "text" => "ZAF - South Africa"],
            ["value" => "ZMB", "text" => "ZMB - Zambia"],
            ["value" => "ZWE", "text" => "ZWE - Zimbabwe"]
        ];

        switch($this->request->input('param')) {
            case 'full':
                return $countries;
                break;
            case 'iso2':
                return $countries_iso2;
                break;
            case 'iso3':
                return $countries_iso3;
                break;
            default:    
                return $countries;
                break;
        }
    }
}