<?php namespace Statamic\Addons\Countries;

use Statamic\Addons\Suggest\Modes\AbstractMode;

class CountriesSuggestMode extends AbstractMode
{
    public function suggestions()
    {
        
        return [
            ["value" => "Andorra", "text" => "Andorra"],
            ["value" => "United Arab Emirates", "text" => "United Arab Emirates"],
            ["value" => "Afghanistan", "text" => "Afghanistan"],
            ["value" => "Antigua and Barbuda", "text" => "Antigua and Barbuda"],
            ["value" => "Anguilla", "text" => "Anguilla"],
            ["value" => "Albania", "text" => "Albania"],
            ["value" => "Armenia", "text" => "Armenia"],
            ["value" => "Angola", "text" => "Angola"],
            ["value" => "Antarctica", "text" => "Antarctica"],
            ["value" => "Argentina", "text" => "Argentina"],
            ["value" => "American Samoa", "text" => "American Samoa"],
            ["value" => "Austria", "text" => "Austria"],
            ["value" => "Australia", "text" => "Australia"],
            ["value" => "Aruba", "text" => "Aruba"],
            ["value" => "Aland Islands ", "text" => "Aland Islands "],
            ["value" => "Azerbaijan", "text" => "Azerbaijan"],
            ["value" => "Bosnia and Herzegovina", "text" => "Bosnia and Herzegovina"],
            ["value" => "Barbados", "text" => "Barbados"],
            ["value" => "Bangladesh", "text" => "Bangladesh"],
            ["value" => "Belgium", "text" => "Belgium"],
            ["value" => "Burkina Faso", "text" => "Burkina Faso"],
            ["value" => "Bulgaria", "text" => "Bulgaria"],
            ["value" => "Bahrain", "text" => "Bahrain"],
            ["value" => "Burundi", "text" => "Burundi"],
            ["value" => "Benin", "text" => "Benin"],
            ["value" => "Saint Barthélemy", "text" => "Saint Barthélemy"],
            ["value" => "Bermuda", "text" => "Bermuda"],
            ["value" => "Brunei Darussalam", "text" => "Brunei Darussalam"],
            ["value" => "Bolivia, Plurinational State of", "text" => "Bolivia, Plurinational State of"],
            ["value" => "Bonaire, Sint Eustatius and Saba", "text" => "Bonaire, Sint Eustatius and Saba"],
            ["value" => "Brazil", "text" => "Brazil"],
            ["value" => "Bahamas", "text" => "Bahamas"],
            ["value" => "Bhutan", "text" => "Bhutan"],
            ["value" => "Bouvet Island", "text" => "Bouvet Island"],
            ["value" => "Botswana", "text" => "Botswana"],
            ["value" => "Belarus", "text" => "Belarus"],
            ["value" => "Belize", "text" => "Belize"],
            ["value" => "Canada", "text" => "Canada"],
            ["value" => "Cocos (Keeling) Islands", "text" => "Cocos (Keeling) Islands"],
            ["value" => "Congo, the Democratic Republic of the", "text" => "Congo, the Democratic Republic of the"],
            ["value" => "Central African Republic", "text" => "Central African Republic"],
            ["value" => "Congo", "text" => "Congo"],
            ["value" => "Switzerland", "text" => "Switzerland"],
            ["value" => "Cote d'Ivoire", "text" => "Cote d'Ivoire"],
            ["value" => "Cook Islands", "text" => "Cook Islands"],
            ["value" => "Chile", "text" => "Chile"],
            ["value" => "Cameroon", "text" => "Cameroon"],
            ["value" => "China", "text" => "China"],
            ["value" => "Colombia", "text" => "Colombia"],
            ["value" => "Costa Rica", "text" => "Costa Rica"],
            ["value" => "Cuba", "text" => "Cuba"],
            ["value" => "Cape Verde", "text" => "Cape Verde"],
            ["value" => "Curaçao", "text" => "Curaçao"],
            ["value" => "Christmas Island", "text" => "Christmas Island"],
            ["value" => "Cyprus", "text" => "Cyprus"],
            ["value" => "Czech Republic", "text" => "Czech Republic"],
            ["value" => "Germany", "text" => "Germany"],
            ["value" => "Djibouti", "text" => "Djibouti"],
            ["value" => "Denmark", "text" => "Denmark"],
            ["value" => "Dominica", "text" => "Dominica"],
            ["value" => "Dominican Republic", "text" => "Dominican Republic"],
            ["value" => "Algeria", "text" => "Algeria"],
            ["value" => "Ecuador", "text" => "Ecuador"],
            ["value" => "Estonia", "text" => "Estonia"],
            ["value" => "Egypt", "text" => "Egypt"],
            ["value" => "Western Sahara", "text" => "Western Sahara"],
            ["value" => "Eritrea", "text" => "Eritrea"],
            ["value" => "Spain", "text" => "Spain"],
            ["value" => "Ethiopia", "text" => "Ethiopia"],
            ["value" => "Finland", "text" => "Finland"],
            ["value" => "Fiji", "text" => "Fiji"],
            ["value" => "Falkland Islands (Malvinas)", "text" => "Falkland Islands (Malvinas)"],
            ["value" => "Micronesia, Federated States of", "text" => "Micronesia, Federated States of"],
            ["value" => "Faroe Islands", "text" => "Faroe Islands"],
            ["value" => "France", "text" => "France"],
            ["value" => "Gabon", "text" => "Gabon"],
            ["value" => "United Kingdom", "text" => "United Kingdom"],
            ["value" => "Grenada", "text" => "Grenada"],
            ["value" => "Georgia", "text" => "Georgia"],
            ["value" => "French Guiana", "text" => "French Guiana"],
            ["value" => "Guernsey", "text" => "Guernsey"],
            ["value" => "Ghana", "text" => "Ghana"],
            ["value" => "Gibraltar", "text" => "Gibraltar"],
            ["value" => "Greenland", "text" => "Greenland"],
            ["value" => "Gambia", "text" => "Gambia"],
            ["value" => "Guinea", "text" => "Guinea"],
            ["value" => "Guadeloupe", "text" => "Guadeloupe"],
            ["value" => "Equatorial Guinea", "text" => "Equatorial Guinea"],
            ["value" => "Greece", "text" => "Greece"],
            ["value" => "South Georgia and the South Sandwich Islands", "text" => "South Georgia and the South Sandwich Islands"],
            ["value" => "Guatemala", "text" => "Guatemala"],
            ["value" => "Guam", "text" => "Guam"],
            ["value" => "Guinea-Bissau", "text" => "Guinea-Bissau"],
            ["value" => "Guyana", "text" => "Guyana"],
            ["value" => "Hong Kong", "text" => "Hong Kong"],
            ["value" => "Heard Island and McDonald Islands", "text" => "Heard Island and McDonald Islands"],
            ["value" => "Honduras", "text" => "Honduras"],
            ["value" => "Croatia", "text" => "Croatia"],
            ["value" => "Haiti", "text" => "Haiti"],
            ["value" => "Hungary", "text" => "Hungary"],
            ["value" => "Indonesia", "text" => "Indonesia"],
            ["value" => "Ireland", "text" => "Ireland"],
            ["value" => "Israel", "text" => "Israel"],
            ["value" => "Isle of Man", "text" => "Isle of Man"],
            ["value" => "India", "text" => "India"],
            ["value" => "British Indian Ocean Territory", "text" => "British Indian Ocean Territory"],
            ["value" => "Iraq", "text" => "Iraq"],
            ["value" => "Iran, Islamic Republic of", "text" => "Iran, Islamic Republic of"],
            ["value" => "Iceland", "text" => "Iceland"],
            ["value" => "Italy", "text" => "Italy"],
            ["value" => "Jersey", "text" => "Jersey"],
            ["value" => "Jamaica", "text" => "Jamaica"],
            ["value" => "Jordan", "text" => "Jordan"],
            ["value" => "Japan", "text" => "Japan"],
            ["value" => "Kenya", "text" => "Kenya"],
            ["value" => "Kyrgyzstan", "text" => "Kyrgyzstan"],
            ["value" => "Cambodia", "text" => "Cambodia"],
            ["value" => "Kiribati", "text" => "Kiribati"],
            ["value" => "Comoros", "text" => "Comoros"],
            ["value" => "Saint Kitts and Nevis", "text" => "Saint Kitts and Nevis"],
            ["value" => "Korea, Democratic People's Republic of", "text" => "Korea, Democratic People's Republic of"],
            ["value" => "Korea, Republic of", "text" => "Korea, Republic of"],
            ["value" => "Kuwait", "text" => "Kuwait"],
            ["value" => "Cayman Islands", "text" => "Cayman Islands"],
            ["value" => "Kazakhstan", "text" => "Kazakhstan"],
            ["value" => "Lao People's Democratic Republic", "text" => "Lao People's Democratic Republic"],
            ["value" => "Lebanon", "text" => "Lebanon"],
            ["value" => "Saint Lucia", "text" => "Saint Lucia"],
            ["value" => "Liechtenstein", "text" => "Liechtenstein"],
            ["value" => "Sri Lanka", "text" => "Sri Lanka"],
            ["value" => "Liberia", "text" => "Liberia"],
            ["value" => "Lesotho", "text" => "Lesotho"],
            ["value" => "Lithuania", "text" => "Lithuania"],
            ["value" => "Luxembourg", "text" => "Luxembourg"],
            ["value" => "Latvia", "text" => "Latvia"],
            ["value" => "Libyan Arab Jamahiriya", "text" => "Libyan Arab Jamahiriya"],
            ["value" => "Morocco", "text" => "Morocco"],
            ["value" => "Monaco", "text" => "Monaco"],
            ["value" => "Moldova, Republic of", "text" => "Moldova, Republic of"],
            ["value" => "Montenegro", "text" => "Montenegro"],
            ["value" => "Saint Martin (French part)", "text" => "Saint Martin (French part)"],
            ["value" => "Madagascar", "text" => "Madagascar"],
            ["value" => "Marshall Islands", "text" => "Marshall Islands"],
            ["value" => "Macedonia", "text" => "Macedonia"],
            ["value" => "Mali", "text" => "Mali"],
            ["value" => "Myanmar", "text" => "Myanmar"],
            ["value" => "Mongolia", "text" => "Mongolia"],
            ["value" => "Macao", "text" => "Macao"],
            ["value" => "Northern Mariana Islands", "text" => "Northern Mariana Islands"],
            ["value" => "Martinique", "text" => "Martinique"],
            ["value" => "Mauritania", "text" => "Mauritania"],
            ["value" => "Montserrat", "text" => "Montserrat"],
            ["value" => "Malta", "text" => "Malta"],
            ["value" => "Mauritius", "text" => "Mauritius"],
            ["value" => "Maldives", "text" => "Maldives"],
            ["value" => "Malawi", "text" => "Malawi"],
            ["value" => "Mexico", "text" => "Mexico"],
            ["value" => "Malaysia", "text" => "Malaysia"],
            ["value" => "Mozambique", "text" => "Mozambique"],
            ["value" => "Namibia", "text" => "Namibia"],
            ["value" => "New Caledonia", "text" => "New Caledonia"],
            ["value" => "Niger", "text" => "Niger"],
            ["value" => "Norfolk Island", "text" => "Norfolk Island"],
            ["value" => "Nigeria", "text" => "Nigeria"],
            ["value" => "Nicaragua", "text" => "Nicaragua"],
            ["value" => "Netherlands", "text" => "Netherlands"],
            ["value" => "Norway", "text" => "Norway"],
            ["value" => "Nepal", "text" => "Nepal"],
            ["value" => "Nauru", "text" => "Nauru"],
            ["value" => "Niue", "text" => "Niue"],
            ["value" => "New Zealand", "text" => "New Zealand"],
            ["value" => "Oman", "text" => "Oman"],
            ["value" => "Panama", "text" => "Panama"],
            ["value" => "Peru", "text" => "Peru"],
            ["value" => "French Polynesia", "text" => "French Polynesia"],
            ["value" => "Papua New Guinea", "text" => "Papua New Guinea"],
            ["value" => "Philippines", "text" => "Philippines"],
            ["value" => "Pakistan", "text" => "Pakistan"],
            ["value" => "Poland", "text" => "Poland"],
            ["value" => "Saint Pierre and Miquelon", "text" => "Saint Pierre and Miquelon"],
            ["value" => "Pitcairn", "text" => "Pitcairn"],
            ["value" => "Puerto Rico", "text" => "Puerto Rico"],
            ["value" => "Palestinian Territory, Occupied", "text" => "Palestinian Territory, Occupied"],
            ["value" => "Portugal", "text" => "Portugal"],
            ["value" => "Palau", "text" => "Palau"],
            ["value" => "Paraguay", "text" => "Paraguay"],
            ["value" => "Qatar", "text" => "Qatar"],
            ["value" => "Reunion", "text" => "Reunion"],
            ["value" => "Romania", "text" => "Romania"],
            ["value" => "Serbia", "text" => "Serbia"],
            ["value" => "Russian Federation", "text" => "Russian Federation"],
            ["value" => "Rwanda", "text" => "Rwanda"],
            ["value" => "Saudi Arabia", "text" => "Saudi Arabia"],
            ["value" => "Solomon Islands", "text" => "Solomon Islands"],
            ["value" => "Seychelles", "text" => "Seychelles"],
            ["value" => "Sudan", "text" => "Sudan"],
            ["value" => "Sweden", "text" => "Sweden"],
            ["value" => "Singapore", "text" => "Singapore"],
            ["value" => "Saint Helena", "text" => "Saint Helena"],
            ["value" => "Slovenia", "text" => "Slovenia"],
            ["value" => "Svalbard and Jan Mayen", "text" => "Svalbard and Jan Mayen"],
            ["value" => "Slovakia", "text" => "Slovakia"],
            ["value" => "Sierra Leone", "text" => "Sierra Leone"],
            ["value" => "San Marino", "text" => "San Marino"],
            ["value" => "Senegal", "text" => "Senegal"],
            ["value" => "Somalia", "text" => "Somalia"],
            ["value" => "Suritext", "text" => "Suritext"],
            ["value" => "Sao Tome and Principe", "text" => "Sao Tome and Principe"],
            ["value" => "El Salvador", "text" => "El Salvador"],
            ["value" => "Sint Maarten (Dutch part)", "text" => "Sint Maarten (Dutch part)"],
            ["value" => "Syrian Arab Republic", "text" => "Syrian Arab Republic"],
            ["value" => "Swaziland", "text" => "Swaziland"],
            ["value" => "Turks and Caicos Islands", "text" => "Turks and Caicos Islands"],
            ["value" => "Chad", "text" => "Chad"],
            ["value" => "French Southern Territories", "text" => "French Southern Territories"],
            ["value" => "Togo", "text" => "Togo"],
            ["value" => "Thailand", "text" => "Thailand"],
            ["value" => "Tajikistan", "text" => "Tajikistan"],
            ["value" => "Tokelau", "text" => "Tokelau"],
            ["value" => "Timor-Leste", "text" => "Timor-Leste"],
            ["value" => "Turkmenistan", "text" => "Turkmenistan"],
            ["value" => "Tunisia", "text" => "Tunisia"],
            ["value" => "Tonga", "text" => "Tonga"],
            ["value" => "Turkey", "text" => "Turkey"],
            ["value" => "Trinidad and Tobago", "text" => "Trinidad and Tobago"],
            ["value" => "Tuvalu", "text" => "Tuvalu"],
            ["value" => "Taiwan, Province of China", "text" => "Taiwan, Province of China"],
            ["value" => "Tanzania, United Republic of", "text" => "Tanzania, United Republic of"],
            ["value" => "Ukraine", "text" => "Ukraine"],
            ["value" => "Uganda", "text" => "Uganda"],
            ["value" => "United States Minor Outlying Islands", "text" => "United States Minor Outlying Islands"],
            ["value" => "United States", "text" => "United States"],
            ["value" => "Uruguay", "text" => "Uruguay"],
            ["value" => "Uzbekistan", "text" => "Uzbekistan"],
            ["value" => "Holy See (Vatican City State)", "text" => "Holy See (Vatican City State)"],
            ["value" => "Saint Vincent and the Grenadines", "text" => "Saint Vincent and the Grenadines"],
            ["value" => "Venezuela, Bolivarian Republic of", "text" => "Venezuela, Bolivarian Republic of"],
            ["value" => "Virgin Islands, British", "text" => "Virgin Islands, British"],
            ["value" => "Virgin Islands, U.S.", "text" => "Virgin Islands, U.S."],
            ["value" => "Viet Nam", "text" => "Viet Nam"],
            ["value" => "Vanuatu", "text" => "Vanuatu"],
            ["value" => "Wallis and Futuna", "text" => "Wallis and Futuna"],
            ["value" => "Samoa", "text" => "Samoa"],
            ["value" => "Yemen", "text" => "Yemen"],
            ["value" => "Mayotte", "text" => "Mayotte"],
            ["value" => "South Africa", "text" => "South Africa"],
            ["value" => "Zambia", "text" => "Zambia"],
            ["value" => "Zimbabwe", "text" => "Zimbabwe"]
        ];

    }
}