name: Countries Suggest Mode
version: 1.0.0
description: Suggest Mode for list of world countries (Full)
url: https://github.com/lesaff/statamicv2-countries
developer: Rudy Affandi
developer_url: https://github.com/lesaff
