name: Forms Suggest Mode
version: 1.0.0
description: Suggest Mode for list of available forms
url: https://github.com/lesaff/statamicv2-suggestmodes
developer: Mike Martin
developer_url: https://github.com/mikemartin
